### PR TITLE
Organize into nice Python package

### PR DESCRIPTION
**Pull request by sauln**
I setup most of the defaults so the cpp code builds with Python, removed some of the extraneous code not required, and organized the repo so it's a little cleaner.

It looks a bit closer to a python package now and should be able to be installed from pypi without too much more work.

I just wanted to let you know this is here.  This package is slowly inching towards something that looks like a python package.

btw, this wrapper looks great! I was working on something similar, but this is a vast improvement.  Maybe after a little more work, we could get this properly setup in the Python Package Index and setup some nice documentation.

### CODE REVIEW

**Comment by ctralie** [comment]
Hey this is great, thanks!  Do you want to make another pull request when you're finished and it's ready to go onto pypi?

**Comment by sauln** [comment]
Most of the big changes are all these. Could you tell me what you think?  I still want to massage the API and add tests until It conforms to scikit style. 

I think it could be smart to break the libraries git connection to the original Ripser and rebrand this as pyripser or rypser or something. What do you think?

**Comment by sauln** [comment]
@ctralie Please look at https://github.com/sauln/ripser.

You can install the library from the test server (https://test.pypi.org/project/ripser/) using the following command:
`pip install --index-url https://test.pypi.org/simple/ ripser`

I've set up continuous integration (Travis), code coverage (Codecov), and the whole library installs as seamlessly as possible.

Please let me know if you have any input. I'd like to push the package to live pypi this weekend.

**Comment by ctralie** [comment]
@sauln 
Sorry for the lag in this, this looks great for a first version!  Some more documentation, example notebooks, etc would help (especially for highlighting what maxdim, thresh, and coeff are in the Rips class constructor), but I think it's fine for now.  Go ahead and put it up there!
Best,
Chris

**Pull request merged**
